// Host adapters for the existing handler-only hook harness. These tests exercise
// business state, not Radix internals. Real DOM/browser tests use actual shadcn.
export const shadcnTestModules: Record<string, Record<string, unknown>> = {
  '@/components/ui/button': { Button: 'button' },
  '@/components/ui/input': { Input: 'input' },
  '@/components/ui/label': { Label: 'label' },
  '@/components/ui/checkbox': { Checkbox: 'input' },
  '@/components/ui/pagination': {
    Pagination: 'nav',
    PaginationContent: 'ul',
    PaginationItem: 'li',
    PaginationLink: 'a',
    PaginationPrevious: 'a',
    PaginationNext: 'a',
    PaginationEllipsis: 'span',
  },
  '@/components/ui/table': {
    Table: 'table',
    TableHeader: 'thead',
    TableFooter: 'tfoot',
    TableBody: 'tbody',
    TableRow: 'tr',
    TableCell: 'td',
    TableHead: 'th',
  },
  '@/components/ui/dialog': {
    Dialog: 'div',
    DialogContent: 'div',
    DialogHeader: 'header',
    DialogTitle: 'h2',
  },
  '@/components/ui/select': {
    Select: 'div',
    SelectTrigger: 'button',
    SelectValue: 'span',
    SelectContent: 'div',
    SelectItem: 'div',
    SelectSeparator: 'hr',
  },
  '@/components/ui/alert': { Alert: 'div', AlertDescription: 'div' },
  '@/components/ui/card': {
    Card: 'div',
    CardContent: 'div',
    CardHeader: 'header',
    CardTitle: 'h2',
    CardDescription: 'p',
  },
  '@/components/DatePicker': { default: 'input' },
  '@/components/ThemeToggle': { ThemeToggle: 'span' },
}
